name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: Install cowsay
          run: sudo apt-get install cowsay -y

        - name: Generate artwork
          run: cowsay -f dragon "I am an dragon, and I breath fire..." >> elephant.txt

        - name: Show my elephant
          run: cat elephant.txt