name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome step
          run: echo "This is my first step"

        - name: List files
          run: ls

        - name: Read file
          run: cat demo.txt
        