name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: Run shell script
          run: |
            chmod a+x my-script.sh
            ./my-script.sh