name: Matix Configuration

on: 
    workflow_dispatch:
    push:
        branches:
            - main
            - '!feature/*'
    pull_request: 
        types:
            - opened
            - closed

jobs:
    deploy:
        strategy:
          fail-fast: true
          max-parallel: 2
          matrix:
            os: [ubuntu-latest, windows-latest, ubuntu-20.04]
            images: [hello-world, alpine]
            exclude:
                - images: alpine
                  os: windows-latest
        runs-on: ${{ matrix.os }}
        steps:
        - name: Echo docker infor
          run: docker info

        - name: Run image on  ${{ matrix.os }}
          run: docker run ${{ matrix.images }}
