name: Matix Configuration

on: workflow_dispatch

jobs:
    deploy:
        strategy:
          matrix:
            os: [ubuntu-latest, windows-latest, ubuntu-20.04]
            images: [hello-world, alpine]
            exclude:
                - images: alpine
                  os: windows-latest
        runs-on: ${{ matrix.os }}
        steps:
        - name: Echo docker infor
          run: docker info

        - name: Run image on  ${{ matrix.os }}
          run: docker run ${{ matrix.images }}
