name: Events and Triggers

on: workflow_dispatch

jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          run: echo "This is from first job"

    deploy_job:
        if: github.ref == 'refs/heads/main'
        timeout-minutes: 1
        needs: build_job
        concurrency: 
            group: prod-deployment
            cancel-in-progress: false
        runs-on: ubuntu-latest
        steps:
        - name: Download dragon
          timeout-minutes: 2
          run: |
            echo "This is from second job"
            sleep 500s