name: My Third Workflow

on: workflow_dispatch

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          run: echo "This is from first job"

    second_job:
        runs-on: ubuntu-latest
        steps:
        - name: Download dragon
          run: echo "This is from second job"