name: Events and Triggers

on: workflow_dispatch

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          run: echo "This is from first job"

    second_job:
        needs: first_job
        runs-on: ubuntu-latest
        steps:
        - name: Download dragon
          run: echo "This is from second job"